#!/usr/bin/env zsh

echo "
This script will delete and recreate all shared and persistent folders.

You should only need to do this if you are having problems with the
the cluster.

NOTE: This will delete all data in the cluster. You will need to
    re-create the keyspace and tables.

"
read -q "REPLY?Press enter to continue: "

echo "Deleting folders..."
sudo rm -rf pgdb-persistent-storage
sudo rm -rf pgadmin-persistent-storage

echo "Recreating folders..."
mkdir pgdb-persistent-storage
mkdir pgadmin-persistent-storage

echo "Setting permissions..."
chmod 777 pgdb-persistent-storage
chmod 777 pgadmin-persistent-storage 

echo "Done.
"    
