#!/usr/bin/env zsh

echo "
# This script will reset the data storage folders for the Cloudera container.
# Once this is done, you will need to setup persistent storage again
#
# Setting up persistent storage involved the following steps:
# 0. Run 'reset-folders script' (which you are doing now)
# 1. Edit docker-compose.yaml: Comment out persistent-storage volume in docker-compose.yml
# 2. Start cloudera container
#      docker-compose up -d
# 3. Get a terminal into the clouder container
#      docker exec -it Cloudera bash
# 4. Copy the contents of /var/lib to the /home/cloudera/DEV01 folder 
#      cp -rfp /var/lib/* /home/cloudera/DEV01
# 5. Exit the container
#      exit
# 6. Stop the container
#      docker-compose down (or, ctrl-c in a terminal where you ran docker-compose up is run)
# 6. Delete the persistent-storage folder
#      rm -rf persistent-storage/*
# 7. Rename the shared-storage folder to persistent-storage.
#      mv shared-storage persistent-storage
# 8. Create a new shared-storage folder, and set permissions
#      mkdir shared-storage
#      chmod 777 shared-storage
# 9. Uncomment the persistent-storage volume in docker-compose.yml
# 10. Start the container
#      docker-compose up -d


"

read -q "REPLY?Press enter to continue: "


echo "Deleting folders..."
sudo rm -rf persistent-storage
sudo rm -rf shared-storage

echo "Recreating folders..."
mkdir persistent-storage
mkdir shared-storage

echo "Setting permissions..."
chmod 777 persistent-storage
chmod 777 shared-storage

echo "
Done. You will need to setup persistent storage again!.

"
