#!/usr/bin/env zsh

echo "
This script will delete and recreate all shared and persistent folders.

You should only need to do this if you are having problems with the
the cluster. 

NOTE: This will delete all data in the cluster. You will need to
    re-create the keyspace and tables.

"""

read -q "REPLY?Press enter to continue: "

echo "###############################"
echo "Deleting folders"
echo "###############################"
rm -rf dse-n1
rm -rf dse-n2
rm -rf dse-n3
rm -rf dse-studio

echo "###############################"
echo "Creating folders"
echo "###############################"
mkdir dse-n1
mkdir dse-n2
mkdir dse-n3
mkdir dse-studio

echo "###############################"
echo "Setting permissions"
echo "###############################"
chmod 777 dse-n1
chmod 777 dse-n2
chmod 777 dse-n3
chmod 777 dse-studio

echo "###############################"
echo "Done"
echo "###############################"
