#!/usr/bin/env zsh

echo "

#########################################################################

DANGER!

THis script will remove all containers from your system.

You only want to do this if you are looking to start over from scratch.

If you've started this script by accident, press CTRL-C to cancel.

##########################################################################
"
read -q "REPLY?Press enter to continue: "

docker stop $(docker ps -a)

docker rm $(docker ps -aq)
