version: '3.8'

services:
  # Node 1
  postgres-node1:
    image: postgres:latest
    container_name: postgres_node1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: shard1
    ports:
      - "6432:5432"
    volumes:
      - node1_data:/var/lib/postgresql/data
    networks:
      - postgres_cluster
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

  # Node 2
  postgres-node2:
    image: postgres:latest
    container_name: postgres_node2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: shard2
    ports:
      - "6433:5432"
    volumes:
      - node2_data:/var/lib/postgresql/data
    networks:
      - postgres_cluster
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

  # Node 3
  postgres-node3:
    image: postgres:latest
    container_name: postgres_node3
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: shard3
    ports:
      - "6434:5432"
    volumes:
      - node3_data:/var/lib/postgresql/data
    networks:
      - postgres_cluster
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

  # pgAdmin 4 Setup
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - 6050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ENABLE_PSQL: "True"
    volumes:
      - pgadmin_data_cluster:/var/lib/pgadmin
    networks:
      - postgres_cluster      
    deploy: 
      resources:
        limits:
          cpus: '1'
          memory: 4G

networks:
  postgres_cluster:
    driver: bridge

volumes:
  node1_data:
  node2_data:
  node3_data:
  pgadmin_data_cluster:
