#!/usr/bin/env zsh

echo "
This script starts a cqlsh session on the DSE Node 3 container.

The shared storage folder is mounted on this container at /shared-storage-3.
"

read -q "REPLY?Press enter to continue: "

echo "###############################"
echo "CQL Shell on DSE Node 3"
echo "###############################"
docker exec -it DSE-N3 cqlsh
