# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
    - 27017:27017    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./persistent-storage:/data/db
      - ./shared-storage:/data/shared
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 8G
 
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/ # note "mongo" is the hostname of the mongo container above
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G

volumes:
  persistent-storage:
  shared-storage: