#!/usr/bin/env zsh

echo "
This script will delete and recreate all shared and persistent folders.

You should only need to do this if you are having problems with the
the cluster.

NOTE: This will delete all data in the cluster. You will need to
    re-create the keyspace and tables.
"

read -q "REPLY?Press enter to continue: "

sudo rm -rf persistent-storage
sudo rm -rf shared-storage

mkdir persistent-storage
mkdir shared-storage

chmod 777 persistent-storage
chmod 777 shared-storage



