#!/usr/bin/env zsh

echo "

#########################################################################

# This script provides the status of all nodes in the cassandra cluster.

# Displays the following:
# - datacenter (the datacenter the node is in)
# - node status (Normal/Leaving/Joining/Moving)
# - IP address (this will be internal to the docker network)
# - load (how much data is stored on the node)
# - tokens (the token range that the node is responsible for)
# - owns (the number of tokens that the node owns)
# - host ID (the unique ID for the node)
# - rack (the rack that the node is in)

NOTE: It may take a minute or two for the nodes to be up and running. You
    can check the status of the nodes while this is happening, but you may 
    see errors about the server not running, or if running, not all nodes 
    recognized in the cluster. If you see this, wait a minute 
    or two and try again.

##########################################################################
"
read -q "REPLY?Press enter to continue: "


echo "###############################"
echo "DSE-N1"
echo "###############################"
docker exec -it DSE-N1 nodetool status

echo "###############################"
echo "DSE-N2"
echo "###############################"
docker exec -it DSE-N2 nodetool status

echo "###############################"
echo "DSE-N3"
echo "###############################"
docker exec -it DSE-N3 nodetool status


